layout_spectrum: 0.4069731526542455
typography_spectrum: 0.721878926968202
color:
  brandStrength: 0.573237327625975
  lightness: 0.480125849833712
  saturation: 0.6816059856209904
  rhythmicContrast: 0.28721613925881684
  brandColors:
    - '#080808'
    - '#9C8573'
    - '#FFFFFF'
    - '#62564A'
    - '#FED5AB'
name: Our Man in Berlin
